services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5434:5434"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: postgres_test
    volumes:
    - ./postgres:/var/lib/postgresql/data